# docker-compose.yml

version: '3.8'

services:
  tensorrt-llm:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../:/workspace
    working_dir: /workspace